// Generated by swiftFilesConstGen
// Input directory: TestInput/
// Files extension: json
// Struct name: JSONFiles
// Do not modify manually

// swiftlint:disable all
struct JSONFiles {

    static let fileExtension = "json"
    
    static let myOtherFile = "My--Other.File"
    static let myFile = "My-File"

}
// swiftlint:enable all
