// Generated by swiftFilesConstGen
// Input directory: TestInput/
// Files extension: json
// Struct name: JSONFiles
// Do not modify manually

// swiftlint:disable all
struct JSONFiles {

    static let file_extension = "json"
    
    static let myOtherFile = "My--Other.File.json"
    static let myFile = "My-File.json"

}
// swiftlint:enable all
