// Generated by swiftFilesConstGen
// Input directory: TestInput/
// Files extension: wav
// Struct name: WAVFiles
// Do not modify manually

// swiftlint:disable all
struct WAVFiles {

    static let fileExtension = "wav"
    
    static let a1someOtherWavFile1234 = "1some_other wav file 1234"
    static let nestedWavFile = "nested wav file"
    static let file = "file"
    static let someWavFile1749 = "some_wav_file-1749"
    static let wavFile1749 = "wav_file-1749"

}
// swiftlint:enable all
