// Generated by swiftFilesConstGen
// Input directory: TestInput/
// Files extension: wav
// Struct name: WAVFiles
// Do not modify manually

// swiftlint:disable all
struct WAVFiles {

    static let file_extension = "wav"
    
    static let a1someOtherWavFile1234 = "1some_other wav file 1234.wav"
    static let nestedWavFile = "nested wav file.wav"
    static let file = "file.wav"
    static let someWavFile1749 = "some_wav_file-1749.wav"
    static let wavFile1749 = "wav_file-1749.wav"

}
// swiftlint:enable all
